name: Broken Links Checker

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  workflow_run:
    workflows: [pages-build-deployment]
    types:
      - completed

jobs:
  check-for-broken-links:
    runs-on: ubuntu-latest
    steps:
      - name: Check Links
        uses: ScholliYT/Broken-Links-Crawler-Action@v3
        with:
          website_url: 'https://rsocket.io'
          exclude_url_prefix: 'mailto:,https://www.linkedin.com,https://linkedin.com,https://www.googletagmanager.com'
          verbose: 'true'
          max_retry_time: 30
          max_retries: 5
          max_depth: 1
      
      - name: Checkout Source
        if: failure()
        uses: actions/checkout@v3
      
      - name: Create Github Issue
        if: failure()
        uses: JasonEtco/create-an-issue@v2.9.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
        with:
          filename: .github/broken-links-issue-template.md
          update_existing: true
          search_existing: open
