name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node.js via NVM
        uses: dcodeIO/setup-node-nvm@master

      - name: Deploy to Github Pages
        env:
          GIT_USER: x-access-token
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "actions@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          if [ -e yarn.lock ]; then
          yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
          npm ci
          else
          npm i
          fi
          npm run deploy
